feat(package): upgarde Typescript to 3.0.3
This is to get past an error when running the tests. Not sure if this
version is too high for Angular, which is built at 9.2.9.

But v9.2.9 throws

```
TypeError: Cannot read property 'getEntryByPath' of undefined
```

According to https://github.com/Microsoft/TypeScript/issues/25047 that
version is the issue. It is fixed in v2.8 and v3. So we have to move or
down.